### PR TITLE
Remove selected class when only a single element is selected

### PR DESCRIPTION
**Pull request by geofreyflores**
Hi, I tried fixing the issue of removing the selected class when only a single item is selected. Looking for any feedback to see if I made the right change and if we can include in the repo. Thanks.

### CODE REVIEW

**Comment by thgreasi** [comment]
It looks correct. Please add a semicolon.
Can you check whether the following also works?:
```js
ui.item.parent().removeClass('' + selectedItemClass);
```
Will review during the weekend.

**Comment by thgreasi** [comment]
Updated previous comment.

**Comment by geofreyflores** [comment]
My bad, will add the semicolon.

> ui.item.parent().removeClass('' + selectedItemClass);

This only seems to remove class from the parent itself and not the children (i.e. the list).

**Comment by thgreasi** [comment]
That was a miss-post from my mobile.
I actually updated that comment right after to read:
```js
ui.item.removeClass('' + selectedItemClass);
```
Can you confirm whether that works? (I'm merging this anyway...)

**Comment by geofreyflores** [comment]
You're right, should've thought of that. Tested and seems to work. I'll include it in. Thanks for the review!

**Comment by thgreasi** [comment]
That's great! thanks! Resolves #28

**Comment by thgreasi** [comment]
Published as v0.7.0. Thanks for your contribution on this :+1:

**Pull request merged**
