### PR TITLE
feat(uiSortableMultiselection): use jQuery UI `handle` option on item selection

### PR DESCRIPTION
**Pull request by ElementRobot**

### CODE REVIEW

**Comment by thgreasi** [comment]
That's great :+1: I will try to review it during the weekend. Any chance you can provide an example to test it?

**Comment by feus4177** [comment]
Sorry, I didn't get a notification for this. Yeah I can try and do that.

**Comment by feus4177** [comment]
Alright I made a small compatibility change, added a demo, and made a codepen for the demo as well. Let me know if there is anything else you need.

**Comment by thgreasi** [comment]
Great! I will try to take a look at it tomorrow!

On Sat, Oct 24, 2015, 22:47 John Feusi <notifications@github.com> wrote:

> Alright I made a small compatibility change, added a demo, and made a
> codepen for the demo as well. Let me know if there is anything else you
> need.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thgreasi/ui-sortable-multiselection/pull/12#issuecomment-150843754>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
@feus4177 This looks ok :+1: , I'm merging it!
спасибо

**Pull request merged**
